### ISSUE TITLE
226 wrong  implementation

### ISSUE THREAD

**Issue by mdm508** [yugaego/cs-study-htdp#1] opened 2022-07-27 23:35 UTC
I think this problem actually wanted you to implement a function that checks if two states are equal. The book did not make it super clear, but just based on the fact that the name of the function is `state=?` suggests that we should be comparing states for equality rather than checking if something is a FSM-state.

```
;; FSM-State FSM-State -> Boolean
;; Determines if s1 and s2 are the same state.
(check-expect (state=? "green" "blue") #false)
(check-expect (state=? "green" "green") #true)
(define (state=? s1 s2)
  (string=? s1 s2))
```

this can later be used in the implementation of `find`

**Comment by yugaego** [comment] 2022-07-28 12:25
> I think this problem actually wanted you to implement a function that checks if two states are equal.

You're right also according to the [*equality predicate* definition](https://htdp.org/2019-02-24/part_one.html#%28part._sec~3aequality1%29) given earlier in the book. 

Would you like to submit a fix for this?

> this can later be used in the implementation of `find`

Yup, and this too.

**Comment by mdm508** [comment] 2022-07-29 00:56
Sure.

**Comment by yugaego** [comment] 2022-07-31 08:54
Let's keep it open until the issue is fixed.

**Comment by yugaego** [comment] 2022-08-23 10:24
Fixed by https://github.com/yugaego/cs-study-htdp/commit/994a1e1e59e63d63a8b4ecda11f7e34574922254.

@mdm508 thank you for reporting the issue.

**Closed as completed by yugaego** 2022-08-23 10:24 UTC
